version: '3.8'
services:
    webserver:
        container_name: webserver-container
        build:
            context: ./
            dockerfile: Dockerfile.Webserver
        ports:
            - '8080:80'
    apigateway:
        container_name: apigateway-container
        build:
            context: ./
            dockerfile: Dockerfile.ApiGateway
        ports:
            - '3000:3000'
    server:
        container_name: server-container
        build:
            context: ./
            dockerfile: Dockerfile.Server
networks:
    my-network:
        driver: bridge
