FROM node:14-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install typescript ts-node

RUN npm install

COPY protos /usr/src/app/protos

COPY api-gateway /usr/src/app/api-gateway

COPY tsconfig.json ./

COPY client /usr/src/app/client

CMD ["npx","ts-node", "api-gateway/index.ts"]